name: re_mind
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  animated_text_kit: ^4.2.3
  cloud_firestore: ^5.6.6
  firebase_auth: ^5.5.0
  firebase_core: ^3.12.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_native_splash: ^2.4.6
  google_fonts: ^6.2.1
  google_sign_in: ^6.3.0
  http: ^1.3.0
  provider: ^6.1.4
  shared_preferences: ^2.5.1
  uuid: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/welcome_background.jpg
    - assets/images/remind_logo.jpg
    - assets/images/questions_background.jpg
    - assets/images/background_main.jpg